### ISSUE TITLE
unable to align center in jspdf

### ISSUE THREAD

**Issue by hamzaakramPaleBlue** [castrix/jspdf-barcode#1]
i want to align barcode in center as we can add style in our doc.text("Item: " , x , y ,{ align: 'center' })..
how can i do this?

**Comment by castrix** [comment]
Hi @hamzaakramPaleBlue , I've added the feature. Try to upgrade the library to version [0.0.8](https://www.npmjs.com/package/jspdf-barcode/v/0.0.8)
let me know if there is still any issue
