### ISSUE TITLE
Generation is not what I expected

### ISSUE THREAD

**Issue by SveRKeR92** [castrix/jspdf-barcode#5]
Hi, great plugin you got here,

Just wanted to give it a try and got a ball of letters merged together instead of a barcode, here is the result : 
![image](https://user-images.githubusercontent.com/70761787/231461089-775b97be-4f16-4065-a8b1-a7d500506b66.png)

Didn't do much different than what is in the readme : 
```
    const barcodeData = "3760372550868";
    PDFDocument.barcode(barcodeData, {
        fontSize: 12,
        textColor: '#000000',
        x: 10,
        y: 85,
    });
```

Maybe you have an idea of what is happening here ?

**Comment by castrix** [comment]
Let me check it out later, might be because different jspdf version

**Comment by SveRKeR92** [comment]
Hi, might be an issue from server side, or directus being not compatible idk 🤷 
I've been building a custom directus endpoint to generate a pdf based on parameter given in the request.

here is what I have now for testing purposes: 
```
import { defineEndpoint } from '@directus/extensions-sdk';
import {jsPDF} from "jspdf";
import "jspdf-barcode";

export default defineEndpoint((router, {services, exceptions}) => {
	router.get('/', (_req, res, next) => {

		const { ItemsService } = services;
		const { ServiceUnavailableException } = exceptions;

		//get product from query
		const productId = _req.query.productId;
		const productService = new ItemsService('Product', { schema: _req.schema, accountability: _req.accountability });

		productService.readByQuery({
			fields: ['*', 'category.*'],
			filter: {
				id: {
					_eq: productId
				}
			}
		}).then((product) => {
			const doc = new jsPDF();
			const barcodeVal = product[0].SKU;
			doc.barcode(barcodeVal, {
				fontSize: 23,
				textColor: "#000000",
				x: 100,
				y: 25.5,
				textOptions: { align: "center" },
			});
			doc.setFont("");
			doc.setFontSize(10);
			doc.text(barcodeVal, 100, 30, {align: "center"} );
			res.setHeader('Content-Type', 'application/pdf');
			res.setHeader('Content-Disposition', 'inline');
			res.send(doc.output());
			return;
              }).catch((err) => {
			console.log(err);
			return next(new ServiceUnavailableException(err.message));
		});
	});
});		
```
Still have the same output as before
![image](https://user-images.githubusercontent.com/70761787/231986906-729c3238-2e8d-4569-ae06-6de9f468b1c3.png)

**Comment by castrix** [comment]
I see, I'll try to reproduce it server-side. otherwise, it might be caused by `directus`

**Comment by castrix** [comment]
Hi there,

I've added an example for [server-side](https://github.com/castrix/jspdf-barcode/tree/main/example-server-side) and fixed the documentation. Please try to update the library to [v0.1.7](https://www.npmjs.com/package/jspdf-barcode/v/0.1.7) or above since I've added some bugfix as well. If it's still not working, then it means that it's not compatible with `directus`.

Thanks for stopping by.

**Comment by castrix** [comment]
oh right, I just re-read your code and I might found the main cause. The import statement here:

```
...
import {jsPDF} from "jspdf";
import "jspdf-barcode";
...
```

should be 

```
...
import jsPDF from "jspdf";
import "jspdf-barcode";
...
```

please try that and let me know if there is still any issue.
